/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utils;

import java.io.FileOutputStream;
import java.io.OutputStream;
import java.util.ArrayList;

public class HtmlBuilder {

    public static String generateError(String title, String subtitle) {
        return "<!DOCTYPE html>\n"
                + "<html lang=\"es\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <title>SSEMM</title>\n"
                + "    <style>\n"
                + "        @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap');\n"
                + "        * {\n"
                + "            font-family: 'Nunito', sans-serif;\n"
                + "        }\n"
                + "        h1 {\n"
                + "            font-size: 24px;\n"
                + "            margin: 0px;\n"
                + "            margin-left: 5px;\n"
                + "        }\n"
                + "        h2 {\n"
                + "            font-size: 18px;\n"
                + "            margin-top: 0;\n"
                + "        }\n"
                + "        .container-flex {\n"
                + "            display: flex;\n"
                + "            align-items: center;\n"
                + "            justify-content: center;\n"
                + "        }\n"
                + "        .container {\n"
                + "            display: flex;\n"
                + "            text-align: center;\n"
                + "        }\n"
                + "        .logo {\n"
                + "            width: 50px;\n"
                + "            height: 50px;\n"
                + "        }\n"
                + "        .text {\n"
                + "            font-size: 24px;\n"
                + "            font-weight: bold;\n"
                + "            padding-left: 5px;\n"
                + "            margin: auto;\n"
                + "        }\n"
                + "        .titlelogo {\n"
                + "            width: 30px;\n"
                + "            height: 30px;\n"
                + "        }\n"
                + "        .text-gray {\n"
                + "            color: #f0f0f0;\n"
                + "        }\n"
                + "        .text-red {\n"
                + "            color: #ff1919;\n"
                + "        }\n"
                + "        .text-red-200 {\n"
                + "            color: #ed7878;\n"
                + "        }\n"
                + "    </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "    <div style=\"border-radius: 20px; background-color: rgb(3, 48, 107); padding: 10px;\">\n"
                + "        <div class=\"container-flex\">\n"
                + "            <div class=\"container\">\n"
                + "                <img class=\"logo\"\n"
                + "                    src=\"https://lh3.googleusercontent.com/u/0/drive-viewer/AITFw-xyNrTsHzJFfoT6ZDqSj33jQeYW173wB-aufa-c4N70gjmT4HNygEBBRe6RWtPEczbHM3BJP5DdH-vYfgePi6ktTbyUKA=w1365-h663\"\n"
                + "                    alt=\"logoSSEM\">\n"
                + "                <div class=\"text text-gray\">SSEM</div>\n"
                + "            </div>\n"
                + "        </div>\n"
                + "        <div class=\"container\">\n"
                + "            <img class=\"titlelogo\" src=\"https://lh3.google.com/u/0/d/10Zec1hFEWsuV-SSUXbI0EgXWsDpWUq1_=w1297-h878-iv1\"\n"
                + "                alt=\"img help\">\n"
                + "            <h1 class=\"text-red\">\n"
                + "                Ocurrió algo : " + title + "</h1>\n"
                + "        </div>\n"
                + "        <h2 class=\"text-gray\"><span class=\"text-red-200\">Descripción: </span>" + subtitle + "</h2>\n"
                + "    </div>\n"
                + "</body>\n"
                + "</html>";
    }

    public static String generateSuccess(String title, String subtitle) {
        return "<!DOCTYPE html>\n"
                + "<html lang=\"es\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <title>SSEMM</title>\n"
                + "    <style>\n"
                + "        @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap');\n"
                + "        * {\n"
                + "            font-family: 'Nunito', sans-serif;\n"
                + "        }\n"
                + "        h1 {\n"
                + "            font-size: 24px;\n"
                + "            margin: 0px;\n"
                + "            margin-left: 5px;\n"
                + "        }\n"
                + "        h2 {\n"
                + "            font-size: 18px;\n"
                + "            margin-top: 0;\n"
                + "        }\n"
                + "        .container-flex {\n"
                + "            display: flex;\n"
                + "            align-items: center;\n"
                + "            justify-content: center;\n"
                + "        }\n"
                + "        .container {\n"
                + "            display: flex;\n"
                + "            text-align: center;\n"
                + "        }\n"
                + "        .logo {\n"
                + "            width: 50px;\n"
                + "            height: 50px;\n"
                + "        }\n"
                + "        .text {\n"
                + "            font-size: 24px;\n"
                + "            font-weight: bold;\n"
                + "            padding-left: 5px;\n"
                + "            margin: auto;\n"
                + "        }\n"
                + "        .titlelogo {\n"
                + "            width: 30px;\n"
                + "            height: 30px;\n"
                + "        }\n"
                + "        .text-gray {\n"
                + "            color: #f0f0f0;\n"
                + "        }\n"
                + "        .text-green {\n"
                + "            color: #0dab57;\n"
                + "        }\n"
                + "        .text-green-200 {\n"
                + "            color: #0ddf6f;\n"
                + "        }\n"
                + "    </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "    <div style=\"border-radius: 20px; background-color: rgb(3, 48, 107); padding: 10px;\">\n"
                + "        <div class=\"container-flex\">\n"
                + "            <div class=\"container\">\n"
                + "                <img class=\"logo\"\n"
                + "                    src=\"https://lh3.googleusercontent.com/u/0/drive-viewer/AITFw-xyNrTsHzJFfoT6ZDqSj33jQeYW173wB-aufa-c4N70gjmT4HNygEBBRe6RWtPEczbHM3BJP5DdH-vYfgePi6ktTbyUKA=w1365-h663\"\n"
                + "                    alt=\"logoSSEM\">\n"
                + "                <div class=\"text text-gray\">SSEM</div>\n"
                + "            </div>\n"
                + "        </div>\n"
                + "        <div class=\"container\">\n"
                + "            <img class=\"titlelogo\" src=\"https://lh3.google.com/u/0/d/1_eFYVvJH1aJ0DqGCjcMR3KMz-jDhp_Jw=w1297-h878-iv1\"\n"
                + "                alt=\"img help\">\n"
                + "            <h1 class=\"text-green-200\">\n"
                + "                Accion realizada : " + title + "</h1>\n"
                + "        </div>\n"
                + "        <h2 class=\"text-gray\"><span class=\"text-green\">Descripción: </span>" + subtitle + "</h2>\n"
                + "    </div>\n"
                + "</body>\n"
                + "</html>";
    }

    public static String generateMapa() {
        String html = "<!DOCTYPE html>\n"
                + "<html lang=\"es\">\n"
                + "\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <title>SSEMM</title>\n"
                + "</head>\n"
                + "\n"
                + "<body>\n"
                + " \n"
                + "    <div id=\"map\" style=\"width: 100%; height: 500px\"></div>\n"
                + "\n"
                + "    <script\n"
                + "        src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCRRNRbdwAPZS6-hW33XJljIbD2228szfg&libraries=places&libraries=visualization\">\n"
                + "    </script>\n"
                + "\n"
                + "    <script>\n"
                + "        var heatmapData = [\n"
                + "            new google.maps.LatLng(37.782, -122.447),\n"
                + "            new google.maps.LatLng(37.782, -122.445),\n"
                + "            new google.maps.LatLng(37.782, -122.443),\n"
                + "            new google.maps.LatLng(37.782, -122.441),\n"
                + "            new google.maps.LatLng(37.782, -122.439),\n"
                + "            new google.maps.LatLng(37.782, -122.437),\n"
                + "            new google.maps.LatLng(37.782, -122.435),\n"
                + "            new google.maps.LatLng(37.785, -122.447),\n"
                + "            new google.maps.LatLng(37.785, -122.445),\n"
                + "            new google.maps.LatLng(37.785, -122.443),\n"
                + "            new google.maps.LatLng(37.785, -122.441),\n"
                + "            new google.maps.LatLng(37.785, -122.439),\n"
                + "            new google.maps.LatLng(37.785, -122.437),\n"
                + "            new google.maps.LatLng(37.785, -122.435)\n"
                + "        ];\n"
                + "\n"
                + "        var sanFrancisco = new google.maps.LatLng(37.774546, -122.433523);\n"
                + "\n"
                + "        map = new google.maps.Map(document.getElementById('map'), {\n"
                + "            center: sanFrancisco,\n"
                + "            zoom: 13,\n"
                + "            mapTypeId: 'satellite'\n"
                + "        });\n"
                + "\n"
                + "        var heatmap = new google.maps.visualization.HeatmapLayer({\n"
                + "            data: heatmapData\n"
                + "        });\n"
                + "\n"
                + "        heatmap.setMap(map);\n"
                + "    </script>\n"
                + "\n"
                + "</body>\n"
                + "\n"
                + "</html>";

        String comando = "Content-Disposition: attachment; filename=\"mapa.html\"\n\n";
        comando += "--separator\n";
        comando += "Content-Type: multipart/mixed; boundary=\"separator\"\n\n";
        comando += "--separator\n";
        comando += html + "\n\n";
        comando += "--separator--";

        return comando;
    }

    public static String generateTabla(String[] headers, ArrayList<String[]> filas) {

        String encabezado = "";
        for (String header : headers) {
            encabezado += "<th>" + header + "</th>\n";
        }

        String body = "";
        for (int i = 0; i < filas.size(); i++) {
            String[] mapa = filas.get(i);

            body += "<tr>\n";
            for (String dato : mapa) {
                body += "<td>" + dato + "</td>\n";
            }
            body += "</tr>\n";
        }

        return "<!DOCTYPE html>\n"
                + "<html lang=\"es\">\n"
                + "<head>\n"
                + "	<meta charset=\"UTF-8\">\n"
                + "	<title>SSEMM</title>\n"
                + "	<style>\n"
                + "		@import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap');\n"
                + "		* {\n"
                + "			font-family: 'Nunito', sans-serif;\n"
                + "		}\n"
                + "\n"
                + "		table {\n"
                + "			width: 100%;\n"
                + "			border-collapse: collapse;\n"
                + "		}\n"
                + "\n"
                + "		th {\n"
                + "			text-align: center;\n"
                + "			padding: 8px;\n"
                + "			background-color: #0bad67;\n"
                + "			color: white;\n"
                + "			border: 1px solid green\n"
                + "		}\n"
                + "\n"
                + "		td {\n"
                + "			text-align: left;\n"
                + "			padding: 8px;\n"
                + "			border: 1px solid green\n"
                + "		}\n"
                + "\n"
                + "		h1 {\n"
                + "			color: green;\n"
                + "			font-size: 24px;\n"
                + "			margin: 0px;\n"
                + "			margin-left: 5px;\n"
                + "		}\n"
                + "\n"
                + "		h2 {\n"
                + "			font-size: 18px;\n"
                + "			margin-top: 0;\n"
                + "		}\n"
                + "		\n"
                + "		.container-flex {\n"
                + "			display: flex;\n"
                + "			align-items: center;\n"
                + "			justify-content: center;\n"
                + "		}\n"
                + "		\n"
                + "		.container {\n"
                + "			display: flex;\n"
                + "			text-align: center;\n"
                + "		}\n"
                + "		\n"
                + "		.logo {\n"
                + "			width: 50px;\n"
                + "			height: 50px;\n"
                + "		}\n"
                + "		\n"
                + "		.text {\n"
                + "			font-size: 24px;\n"
                + "			font-weight: bold;\n"
                + "			padding-left: 5px;\n"
                + "			margin: auto;\n"
                + "		}\n"
                + "		\n"
                + "		.titlelogo {\n"
                + "			width: 30px;\n"
                + "			height: 30px;\n"
                + "		}\n"
                + "		\n"
                + "		.border-b {\n"
                + "			border-bottom: 0px !important;\n"
                + "		}\n"
                + "		\n"
                + "		.border-bt {\n"
                + "			border-bottom: 0px !important;\n"
                + "			border-top: 0px !important;\n"
                + "		}\n"
                + "		.text-gray{\n"
                + "			color: #777;\n"
                + "		}\n"
                + "		.text-green {\n"
                + "			color: green;\n"
                + "		}\n"
                + "\n"
                + "		.text-red {\n"
                + "			color: red;\n"
                + "		}\n"
                + "\n"
                + "		.text-blue {\n"
                + "			color: blue;\n"
                + "		}\n"
                + "\n"
                + "		.text-yellow {\n"
                + "			color: orange;\n"
                + "		}\n"
                + "		.text-little{\n"
                + "			font-size: 11px;\n"
                + "		}\n"
                + "		.text-blue-200{\n"
                + "			color: #0099ff;\n"
                + "		}\n"
                + "		p{\n"
                + "			margin: 0px;\n"
                + "		}\n"
                + "	</style>\n"
                + "</head>\n"
                + "<body>\n"
                + "	<div class=\"container-flex\">\n"
                + "		<div class=\"container\">\n"
                + "			<img class=\"logo\"\n"
                + "				src=\"https://lh3.googleusercontent.com/u/0/drive-viewer/AITFw-xyNrTsHzJFfoT6ZDqSj33jQeYW173wB-aufa-c4N70gjmT4HNygEBBRe6RWtPEczbHM3BJP5DdH-vYfgePi6ktTbyUKA=w1365-h663\"\n"
                + "				alt=\"logoSSEM\">\n"
                + "			<div class=\"text\">SSEM</div>\n"
                + "		</div>\n"
                + "	</div>\n"
                + "	<div class=\"container\">\n"
                + "		<h1>Lista de Mapas</h1>\n"
                + "	</div>\n"
                + "	<h2 class=\"text-gray\">Aqui tienes todos los mapas del proyecto</h2>\n"
                + "	<table>\n"
                + "		<thead>\n"
                + "			<tr>\n"
                + encabezado
                + "			</tr>\n"
                + "		</thead>\n"
                + "		<tbody>\n"
                + "			<tr>\n"
                + body
                + "			</tr>\n"
                + "		</tbody>\n"
                + "	</table>\n"
                + "</body>\n"
                + "</html>";
    }

}